- import_playbook: playbooks/01-node-exporter.yml
- import_playbook: playbooks/02-prometheus.yml
- import_playbook: playbooks/03-grafana.yml
# - import_playbook: playbooks/04-alertmanager.yml
- import_playbook: playbooks/04-nginx-exporter.yml
